name: sample_crud
description: An empty Aqueduct application.
version: 0.0.1
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  aqueduct: 3.3.0+1
  jaguar_jwt: ^2.1.6
  dbcrypt: ^1.0.0
  dotenv: ^2.0.0
  mime: ^0.9.6+3
  http_server: ^0.9.8+3

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0